# Generated by Django 4.0.4 on 2022-05-29 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 29, 19, 40, 2, 527305, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
